In [2]:
#import packages
import os
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

ini_data = pd.ExcelFile('DATA_VKR_FIN.xlsx')
findf = ini_data.parse('Fin_Data')
findata = findf[['Eq_TL', 'ShtDebt_Eq', 'Eq_TA', 'D_EBIT', 'Cash_TA', 'Cur_rat',
                'Tan_TA', 'ROE', 'ROA', 'ROCE', 'EBIT_IntEx', 'S_TA', 'CFO_S', 'CFO_OperPr',
                'lnTA', 'GPM', 'Pretax_margin']]
findata.head()

,Eq_TL,ShtDebt_Eq,Eq_TA,D_EBIT,Cash_TA,Cur_rat,Tan_TA,ROE,ROA,ROCE,EBIT_IntEx,S_TA,CFO_S,CFO_OperPr,lnTA,GPM,Pretax_margin
0,157.465863,0.006351,0.717348,0.046795,0.018795,4.364490,0.132215,0.091389,0.068348,0.087232,11.739958,1.584598,-0.193541,1.908157,21.637539,0.106725,0.034251
1,0.000000,0.000000,0.689469,0.000000,0.067451,3.369437,0.148554,0.150758,0.105956,0.147199,0.000000,1.444532,0.064392,0.844310,21.721952,0.172304,0.092864
2,0.000000,0.000000,0.478085,0.000000,0.024046,1.894755,0.424870,-0.161020,-0.092264,-0.174795,0.000000,1.088550,-0.033797,-0.905197,21.926716,0.180730,-0.047342
3,24.849515,0.040242,0.476917,0.111569,0.002983,1.882382,0.378735,0.251112,0.119885,0.217434,47.854494,1.117112,-0.033746,0.703612,22.214210,0.046622,0.142394
4,1.365994,0.732068,0.126975,-8.900647,0.005281,1.086451,0.504518,-0.080013,-0.016428,-0.082351,-3.750933,0.658542,-0.110774,-10.164585,23.457502,0.081356,-0.012054

In [4]:
desc_stat_fin = findata.describe()
desc_stat_fin.to_excel('desc_stat_fin.xlsx')

In [6]:
qualdf = ini_data.parse('Qualitative_data (с нулями)')
qualdata = qualdf[['Comp_age', 'Corp_group', 'Ind_innov', 'M_founder', 'Man_change',
                  'Is_Europe', 'Is_Asia', 'Is_service', 'Is_SME', 'Is_LLC']]
desc_qualdata = qualdata.describe()
desc_qualdata.to_excel('desc_qualdata.xlsx')

In [7]:
macro = ini_data.parse('Macrodata')
macrodata = macro[['Unempl_rat', 'Inf_FedReg']]
desc_macrodata = macrodata.describe()
desc_macrodata.to_excel('desc_macrodata.xlsx')